name: BuildTeamTools
main: net.buildtheearth.buildteamtools.BuildTeamTools
api-version: 1.13
version: ${version}
description: ${description}
author: MineFact, frikandelworst, George112n, ELgamer, SirJodelstein, Zoriot
softdepend: [WorldEdit, HeadDatabase, PlotSystem-Terra]

commands:
  buildteamtools:
    description: Main command of the Build Team Tools plugin.
    usage: /buildteamtools
    aliases: [btt]
  generate:
    description: Allows usage of the Generator Tool.
    usage: /generate
    aliases: [gen, g]
  navigator:
    description: Opens the universal navigator.
    usage: /navigator
    aliases: [nav, navigate]
  warp:
    description: Command for managing warps.
    usage: /warp <subcommand>
    aliases: [ warps, wp ]
  warpbt:
    description: Opens the warp menu for the specified BuildTeam
    usage: /warpsbt <team>
    aliases: [ wbt, wpt, warpsbuildteam, warpsbt ]
  kml:
    description: kml pasting and parsing
    usage: /kml
    aliases: [geopoints, geopath, georing, geosurface]
  blockpalette:
    description: Opens the block palette menu.
    usage: /blockpalette [filter|menu|filter <filter1> <filter2> ...]
    aliases: [bp, blocks]
    permission: blockpalette.use
  buildteam:
    description: Sends the player to the specified BuildTeam
    usage: /buildteam <team>
    aliases: [bt]
permissions:
  blockpalette.use:
    description: Allows players to use /blockpalette
    default: true
  btt.bp.edit:
    description: Allows players to create and edit custom block palettes
    default: op
