name: BuildTeamTools
main: net.buildtheearth.BuildTeamTools
api-version: 1.13
version: 0.1.3-alpha
author: MineFact, frikandelworst, George112n, ELgamer, SirJodelstein
softdepend: [WorldEdit, HeadDatabase]

commands:
  buildteam:
    description: Main command of the Build Team plugin.
    usage: /buildteam
    aliases:
      - btt
      - buildteamtools
  generate:
    description: Allows usage of the Generator Tool.
    usage: /generate
    aliases:
      - gen
      - g
  navigator:
    description: Opens the universal navigator.
    usage: /navigator
    aliases:
      - nav
      - navigate
  warp:
    description: Command for managing warps.
    usage: /warp <subcommand>
    aliases:
      - warps
  temporary:
    description: Temporary test command.
    usage: /temporary
  kml:
    description: kml pasting and parsing
    usage: /kml
    aliases:
     - geopoints
     - geopath
     - georing
     - geosurface
  createplot:
    description: Creates a new plot for the PlotSystem.
    usage: /createplot
    permission: plotsystem.createplot
  pasteplot:
    description: Pastes a plot manually with specific ID
    usage: /pasteplot <ID>
    permission: plotsystem.pasteplot
  plotsystemterra:
    description: Sends info about the plugin
    usage: /plotsystemterra