name: BuildTeamTools
main: net.buildtheearth.buildteamtools.BuildTeamTools
api-version: 1.13
version: ${version}
description: ${description}
author: MineFact, frikandelworst, George112n, ELgamer, SirJodelstein, Zoriot
softdepend: [ WorldEdit, HeadDatabase, PlotSystem-Terra, BlueMap ]

commands:
  buildteamtools:
    description: Main command of the Build Team Tools plugin.
    usage: /buildteamtools
    aliases: [ btt ]
  generate:
    description: Allows usage of the Generator Tool.
    usage: /generate
    aliases: [ gen, g ]
  navigator:
    description: Opens the universal navigator.
    usage: /navigator
    aliases: [ nav, navigate ]
  explore:
    description: Opens the BuildTeams explore menu.
    usage: /explore
  warp:
    description: Command for managing warps.
    usage: /warp <subcommand>
    aliases: [ warps, wp ]
  warpbt:
    description: Opens the warp menu for the specified BuildTeam
    usage: /warpsbt <team>
    aliases: [ wbt, wpt, warpsbuildteam, warpsbt ]
  kml:
    description: kml pasting and parsing
    usage: /kml
    aliases: [ geopoints, geopath, georing, geosurface ]
  blockpalette:
    description: Opens the block palette menu.
    usage: /blockpalette [filter|menu|filter <filter1> <filter2> ...]
    aliases: [ bp, blocks ]
    permission: btt.bp.use
  buildteam:
    description: Sends the player to the specified BuildTeam
    usage: /buildteam <team>
    aliases: [ bt ]
permissions:
  btt.permpack.visitor:
    description: Contains all permissions for visitors / everyone
    default: op
    children:
      btt.navigator.use: true
      btt.warp.use: true
      btt.bp.use: true
  btt.permpack.builder:
    description: Contains all permissions for builders / trusted players
    default: op
    children:
      btt.generator.use: true
  btt.permpack.admin:
    description: Contains all permissions for admins
    default: op
    children:
      btt.command.use: true
      btt.command.cache: true
      btt.command.checkForUpdates: true
      btt.command.communicators: true
      btt.command.debug: true
      btt.command.reload: true
      btt.warp.create: true
      btt.warp.edit: true
      btt.warp.delete: true
      btt.warp.group.create: true
      btt.warp.group.edit: true
      btt.warp.group.delete: true
      btt.notify.update: true
      btt.bp.edit: true

  btt.bp.use:
    description: Allows players to use /blockpalette
    default: op
  btt.bp.edit:
    description: Allows players to create and edit custom block palettes
    default: op
